esudo: required
dist: trusty
language: python
python:
  - "2.7"
  - "3.5"

env:
  global:
    - DJANGO_SETTINGS_MODULE=api.settings
    - PYTHONPATH=$HOME/builds/polyaxon/polyaxon-api/api
    - PIP_USE_MIRRORS=true
  matrix:
    - TENSORFLOW_VERSION=1.2.1

services:
  - postgresql

addons:
  postgresql: "9.6"

install:
  # http://conda.pydata.org/docs/travis.html
  - sudo apt-get update
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy scipy six pytest-cov h5py
  - source activate test-environment
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      conda install pil;
    elif [[ "$TRAVIS_PYTHON_VERSION" == "3.5" ]]; then
      conda install Pillow;
    fi
  - pip install -q tensorflow==$TENSORFLOW_VERSION
  - python setup.py -q install
  - pip install -r requirements-test.txt

before_script:
  - psql -c "CREATE DATABASE travis_ci_test;" -U postgres
  - cp config/local.json api/api/env_vars/local.json

script:
  - python setup.py test

after_success:
  - codecovv
