version: "3"

services:
  web:
    build:
      context: .
      dockerfile: ./DockerfileDev
    environment:
      WAIT_FOR_PORTS: "postgres:5432"
      TESTING: 1
      DJANGO_SETTINGS_MODULE: api.settings
