site_name: Polyaxon Documentation
site_url: http://polyaxon.com
site_author: Polyaxon Team
repo_url: https://github.com/polyaxon/polyaxon
repo_name: polyaxon/polyaxon
site_favicon: 'images/favicon.ico'
docs_dir: docs
site_description: 'Documentation for polyaxon, a Deep Learning Platform.'
theme: material
extra:
  logo: 'images/logo_white.svg'
  palette:
    primary: 'blue grey'
    accent: 'light blue'
  social:
    - type: 'github'
      link: 'https://github.com/polyaxon'
    - type: 'twitter'
      link: 'https://twitter.com/polyaxonai'

dev_addr: '0.0.0.0:8000'
google_analytics: ['UA-89493331-1', 'polyaxon.com']
copyright: Copyright &copy; 2017 Polyaxon

markdown_extensions:
  - codehilite
  - admonition
  - codehilite
  - footnotes

pages:
- Home: index.md
- Getting started: getting_started.md
- Experiments:
  - Introduction: experiments/introduction.md
  - Expermient: experiments/experiment.md
  - RLExpermient: experiments/rl_experiment.md
  - Utils: experiments/utils.md
- Estimators:
  - Estimator: estimators/estimator.md
- Agents:
  - Agent: agents/agent.md
  - PGAgent: agents/pg_agent.md
  - TRPOAgent: agents/trpo_agent.md
- Hooks:
  - GeneralHooks: hooks/general_hooks.md
  - StepHooks: hooks/step_hooks.md
  - EpisodeHooks: hooks/episode_hooks.md
- Models:
  - Base Model: models/base_model.md
  - Base RL Q Model: models/base_rl_q_model.md
  - Base RL PG Model: models/base_rl_pg_model.md
  - Models: models/models.md
  - RLQModels: models/rl_q_models.md
  - RLPGModels: models/rl_pg_models.md
  - Summerizer: models/summarizer.md
- Layers:
  - Introduction: layers/introduction.md
  - Advanced Actications: layers/advanced_activations.md
  - Convolutional: layers/convolutional.md
  - Convolutional Reccurent: layers/convolutional_recurrent.md
  - Core: layers/core.md
  - Embedding: layers/embeddings.md
  - Local: layers/local.md
  - Merge: layers/merge.md
  - Moise: layers/noise.md
  - Normalizations: layers/normalizations.md
  - Pooling: layers/pooling.md
  - Recurrent: layers/recurrent.md
  - Wrappers: layers/wrappers.md
- Bridges:
  - Base Bridge: bridges/base_bridge.md
  - Bridges: bridges/bridges.md
- Processing:
  - Categorical Vocabulary: processing/categorical_vocabulary.md
  - Vocabulary Processor: processing/vocabulary_processor.md
  - Image: processing/image.md
  - Input function: processing/input_fn.md
  - Pipelines: processing/pipelines.md
  - Data Decoders: processing/data_decoders.md
  - Data Providers: processing/data_providers.md
- Activations: activations.md
- Losses: losses.md
- Metrics: metrics.md
- Optimizers: optimizers.md
- Initializations: initializers.md
- Constraints: constraints.md
- Regularizations: regularizers.md
- Variables: variables.md
- RL:
  - Environments: rl/environments.md
  - Explorations: rl/explorations.md
  - Memories: rl/memories.md
  - utils: rl/utils.md
- Libs:
  - Getters: libs/getters.md
  - Utils: libs/utils.md
- Datasets:
  - Converters: datasets/converters.md
  - Cifar10: datasets/cifar10.md
  - Flowers17: datasets/flowers17.md
  - Mnist: datasets/mnist.md
- Contributing: CONTRIBUTING.md
