site_name: Polyaxon Documentation
site_url: http://polyaxon.com
site_author: Polyaxon Team
repo_url: https://github.com/polyaxon/polyaxon
repo_name: polyaxon/polyaxon
site_favicon: 'images/favicon.ico'
docs_dir: docs
site_description: 'Documentation for polyaxon, a Deep Learning Platform.'
theme: material
extra:
  logo: 'images/logo_white.svg'
  palette:
    primary: 'blue grey'
    accent: 'light blue'
  social:
    - type: 'github'
      link: 'https://github.com/polyaxon'
    - type: 'twitter'
      link: 'https://twitter.com/polyaxonai'

extra_css:
    - css/style.css

dev_addr: '0.0.0.0:8000'
google_analytics: ['UA-89493331-1', 'polyaxon.com']
copyright: Copyright &copy; 2017 Polyaxon

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: False
  - footnotes

pages:
- Home: index.md
- Quick Start With Polyaxon: quick_start.md
- Installation Requirements & Setup:
  - Introduction: installation/introduction.md
  - Tools & Requirements: installation/tools_and_requirements.md
  - Instal Kuberenetes: installation/install_kubernetes.md
  - Configure Kuberenetes & Helm: installation/configure_kubernetes.md
  - Install Polyaxon Helm Chart: installation/polyaxon_helm.md
  - Install Polyaxon CLI: installation/polyaxon_cli.md
  - Turn Off Polyaxon: installation/turn_off_polyaxon.md
- Experimentation Workflow:
  - Polyaxon Concepts: experimentation/concepts.md
  - Projects: experimentation/projects.md
  - Experiment Groups & Hyperparams Search: experimentation/experiment_groups.md
  - Experiments & Distributed Runs: experimentation/experiments.md
  - Jobs: experimentation/jobs.md
- Management:
  - Intorduction: management/introduction.md
  - Admin Users: management/admins.md
  - Users Management: management/users.md
- Customization:
  - Extend Polyaxon Deployments: customization/extend_deployments.md
  - Customize Run Environment: customization/customize_run_environment.md  # settings, resources,
- Reference Polyaxon CLI:
  - CLI Assumptions: polyaxon_cli/assumptions.md
  - CLI Commnands: polyaxon_cli/commands.md
- Reference Polyaxonfile Specification:
  - Introduction: polyaxonfile_specification/introduction.md
  - Sections: polyaxonfile_specification/sections.md
  - Exec File: polyaxonfile_specification/exec_file.md
  - Model File: polyaxonfile_specification/model_file.md
- Reference Polyaxon Helm: reference_polyaxon_helm.md
- Reference Polyaxon Lib:
  - Introduction: polyaxon_lib/introduction.md
  - Models: polyaxon_lib/models.md
  - Layers:
    - Introduction: polyaxon_lib/layers/introduction.md
    - Advanced Actications: polyaxon_lib/layers/advanced_activations.md
    - Convolutional: polyaxon_lib/layers/convolutional.md
    - Convolutional Reccurent: polyaxon_lib/layers/convolutional_recurrent.md
    - Core: polyaxon_lib/layers/core.md
    - Embedding: polyaxon_lib/layers/embeddings.md
    - Local: polyaxon_lib/layers/local.md
    - Merge: polyaxon_lib/layers/merge.md
    - Moise: polyaxon_lib/layers/noise.md
    - Normalizations: polyaxon_lib/layers/normalizations.md
    - Pooling: polyaxon_lib/layers/pooling.md
    - Recurrent: polyaxon_lib/layers/recurrent.md
    - Wrappers: polyaxon_lib/layers/wrappers.md
  - Bridges: polyaxon_lib/bridges.md
  - Processing:
    - Image: polyaxon_lib/processing/image.md
    - Pipelines: polyaxon_lib/processing/pipelines.md
  - Losses: polyaxon_lib/losses.md
  - Metrics: polyaxon_lib/metrics.md
  - Optimizers: polyaxon_lib/optimizers.md
  - Initializations: polyaxon_lib/initializations.md
  - Constraints: polyaxon_lib/constraints.md
  - Regularizations: polyaxon_lib/regularizers.md
- Contributing: CONTRIBUTING.md
