---
name: conv_mnsit
output_dir: "/tmp/polyaxon_logs/conv_mnsit"
run_config:
  save_checkpoints_steps: 100
train_input_data_config:
  pipeline_config:
    module: TFRecordImagePipeline
    batch_size: 64
    num_epochs: 5
    shuffle: true
    dynamic_pad: false
    params:
      data_files: "../data/mnist/mnist_train.tfrecord"
      meta_data_file: "../data/mnist/meta_data.json"
eval_input_data_config:
  pipeline_config:
    module: TFRecordImagePipeline
    batch_size: 32
    num_epochs: 1
    shuffle: true
    dynamic_pad: false
    params:
      data_files: "../data/mnist/mnist_eval.tfrecord"
      meta_data_file: "../data/mnist/meta_data.json"
estimator_config:
  output_dir: "/tmp/polyaxon_logs/conv_mnsit"
model_config:
  module: Classifier
  loss:
    module: sigmoid_cross_entropy
  metrics:
  - module: streaming_accuracy
  optimizer_config:
    module: adam
    learning_rate: 0.001
  one_hot_encode: true
  n_classes: 10
  graph_config:
    name: convnet
    features:
    - image
    definition:
    - - Conv2d
      - num_filter: 32
        filter_size: 3
        strides: 1
        activation: elu
        regularizer: l2_regularizer
    - - MaxPool2d
      - kernel_size: 2
    - - LocalResponseNormalization
      - {}
    - - Conv2d
      - num_filter: 64
        filter_size: 3
        activation: relu
        regularizer: l2_regularizer
    - - MaxPool2d
      - kernel_size: 2
    - - LocalResponseNormalization
      - {}
    - - FullyConnected
      - num_units: 128
        activation: tanh
    - - Dropout
      - keep_prob: 0.8
    - - FullyConnected
      - num_units: 256
        activation: tanh
    - - Dropout
      - keep_prob: 0.8
    - - FullyConnected
      - num_units: 10
