---
name: lenet_mnsit
output_dir: "/tmp/polyaxon_logs/lenet"
eval_every_n_steps: 10
train_steps_per_iteration: 1000
run_config:
  save_checkpoints_steps: 100
train_input_data_config:
  pipeline_config:
    module: TFRecordImagePipeline
    batch_size: 64
    num_epochs: 5
    shuffle: true
    dynamic_pad: false
    params:
      data_files: "../data/mnist/mnist_train.tfrecord"
      meta_data_file: "../data/mnist/meta_data.json"
eval_input_data_config:
  pipeline_config:
    module: TFRecordImagePipeline
    batch_size: 32
    num_epochs: 1
    shuffle: true
    dynamic_pad: false
    params:
      data_files: "../data/mnist/mnist_eval.tfrecord"
      meta_data_file: "../data/mnist/meta_data.json"
estimator_config:
  output_dir: "/tmp/polyaxon_logs/lenet"
model_config:
  summaries: all
  module: Classifier
  loss_config:
    module: softmax_cross_entropy
  eval_metrics_config:
  - module: streaming_true_positives
  - module: streaming_true_negatives
  - module: streaming_false_positives
  - module: streaming_false_negatives
  - module: streaming_recall
  - module: streaming_auc
  - module: streaming_accuracy
  - module: streaming_precision
  optimizer_config:
    module: adam
    learning_rate: 0.007
    decay_type: exponential_decay
    decay_rate: 0.2
  one_hot_encode: true
  n_classes: 10
  graph_config:
    name: lenet
    features:
    - image
    definition:
    - - Conv2d
      - num_filter: 32
        filter_size: 5
        strides: 1
        regularizer: l2_regularizer
    - - MaxPool2d
      - kernel_size: 2
    - - Conv2d
      - num_filter: 64
        filter_size: 5
        regularizer: l2_regularizer
    - - MaxPool2d
      - kernel_size: 2
    - - FullyConnected
      - num_units: 1024
        activation: tanh
    - - FullyConnected
      - num_units: 10
