---
name: residual_net_mnist
output_dir: "/tmp/polyaxon_logs/res_net_mnist"
train_steps_per_iteration: 100
run_config:
  save_checkpoints_steps: 100
train_input_data_config:
  pipeline_config:
    module: TFRecordImagePipeline
    batch_size: 64
    num_epochs: 1
    shuffle: true
    dynamic_pad: false
    params:
      data_files: "../data/mnist/mnist_train.tfrecord"
      meta_data_file: "../data/mnist/meta_data.json"
eval_input_data_config:
  pipeline_config:
    module: TFRecordImagePipeline
    batch_size: 32
    num_epochs: 1
    shuffle: true
    dynamic_pad: false
    params:
      data_files: "../data/mnist/mnist_eval.tfrecord"
      meta_data_file: "../data/mnist/meta_data.json"
estimator_config:
  output_dir: "/tmp/polyaxon_logs/res_net_mnist"
model_config:
  summaries: all
  module: Classifier
  loss:
    module: softmax_cross_entropy
  metrics:
  - module: streaming_accuracy
  optimizer_config:
    module: adam
    learning_rate: 0.07
    decay_type: exponential_decay
    decay_rate: 0.2
  one_hot_encode: true
  n_classes: 10
  graph_config:
    name: resnet
    features:
    - image
    definition:
    - - Conv2d
      - num_filter: 64
        filter_size: 3
        activation: relu
    - - ResidualBottleneck
      - num_blocks: 3
        bottleneck_size: 16
        out_channels: 64
    - - ResidualBottleneck
      - num_blocks: 1
        bottleneck_size: 32
        out_channels: 128
        downsample: true
    - - ResidualBottleneck
      - num_blocks: 2
        bottleneck_size: 32
        out_channels: 128
    - - ResidualBottleneck
      - num_blocks: 1
        bottleneck_size: 64
        out_channels: 256
        downsample: true
    - - ResidualBottleneck
      - num_blocks: 2
        bottleneck_size: 64
        out_channels: 256
    - - BatchNormalization
      - {}
    - - GlobalAvgPool
      - {}
    - - FullyConnected
      - num_units: 10
