site_name: Polyaxon Documentation
site_url: http://polyaxon.com
repo_url: https://github.com/polyaxon/polyaxon
repo_name: polyaxon/polyaxon
site_favicon: 'images/favicon.ico'
docs_dir: sources
site_description: 'Documentation for polyaxon, a python Deep Learning library for TensorFlow.'
theme: material
extra:
  logo: 'assets/images/logo_white.svg'
  palette:
    primary: 'blue grey'
    accent: 'light blue'
  social:
    - type: 'github'
      link: 'https://github.com/polyaxon'
    - type: 'twitter'
      link: 'https://twitter.com/polyaxonai'

dev_addr: '0.0.0.0:8000'
google_analytics: ['UA-89493331-1', 'polyaxon.com']

markdown_extensions:
  - codehilite

pages:
- Home: index.md
- Getting started: getting_started.md
- Experiments:
  - Introduction: experiments/introduction.md
  - Expermient: experiments/experiment.md
  - RLExpermient: experiments/rl_experiment.md
  - Utils: experiments/utils.md
- Estimators:
  - Estimator: estimators/estimator.md
  - Agent: estimators/agent.md
- Hooks:
  - GeneralHooks: hooks/general_hooks.md
  - StepHooks: hooks/step_hooks.md
  - EpisodeHooks: hooks/episode_hooks.md
- Models:
  - Base Model: models/base_model.md
  - Base RL Q Model: models/base_rl_q_model.md
  - Models: models/models.md
  - RLQModels: models/rl_q_models.md
  - Summerizer: models/summarizer.md
- Layers:
  - Introduction: layers/introduction.md
  - Core Layers: layers/core.md
  - Convolutional Layers: layers/convolutional.md
  - Recurrent Layers: layers/recurrent.md
  - Embedding Layers: layers/embeddings.md
- Bridges:
  - Base Bridge: bridges/base_bridge.md
  - Bridges: bridges/bridges.md
- Encoders:
  - Encoder: encoders/encoder.md
- Decoders:
  - Decoder: decoders/decoder.md
- Processing:
  - Categorical Vocabulary: processing/categorical_vocabulary.md
  - Vocabulary Processor: processing/vocabulary_processor.md
  - Image: processing/image.md
  - Input function: processing/input_fn.md
  - Pipelines: processing/pipelines.md
  - Data Decoders: processing/data_decoders.md
  - Data Providers: processing/data_providers.md
- Activations: activations.md
- Losses: losses.md
- Metrics: metrics.md
- Optimizers: optimizers.md
- Initializations: initializations.md
- Regularizations: regularizations.md
- Explorations: explorations.md
- Variables: variables.md
- Subgraph: subgraph.md
- Libs:
  - Configs: libs/configs.md
  - Getters: libs/getters.md
  - Utils: libs/utils.md
- Datasets:
  - Converters: datasets/converters.md
  - Cifar10: datasets/cifar10.md
  - Flowers17: datasets/flowers17.md
  - Mnist: datasets/mnist.md
- Contributing: CONTRIBUTING.md
